spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: eureka-client-dev
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不向中心注册自己
    fetch-registry: false # false 表示自己就是注册中心，我的指责就是维护服务实例，并不需要去检索服务
    service-url:
      #      单机
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
spring:
  profiles: test
  application:
    name: eureka-client-test
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不向中心注册自己
    fetch-registry: false # false 表示自己就是注册中心，我的指责就是维护服务实例，并不需要去检索服务
    service-url:
      #      单机
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/